version: '3.8'
services:
  database:
    image: docker.io/mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: issue_tracker
    ports:
      - "3306:3306"
  api:
    build: ./apps/api/
    restart: unless-stopped
    volumes:
      - ./apps/api:/srv/app
    depends_on:
      - database
  caddy:
    image: docker.io/caddy:2.5.0-beta.1-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apps/api/Caddyfile:/etc/caddy/Caddyfile
      - ./apps/api:/srv/app
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api
volumes:
  caddy_data:
    external: true
  caddy_config:
